# Generated by Django 4.2 on 2023-04-27 12:22

from django.db import migrations, models
import feed.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='type',
        ),
        migrations.AddField(
            model_name='mediafiles',
            name='type',
            field=models.CharField(default='image', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentfiles',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=feed.models.get_comment_filename, verbose_name='comment_files'),
        ),
    ]
